### PR TITLE
Update arrows.md

### PR DESCRIPTION
**Pull request by beaufortfrancois**
I guess you meant arrow functions do bind `this` right?

### CODE REVIEW

**Comment by saspre** [comment]
No I meant that they do not bind `this`. They do not bind anything to
`this`. `this` is the same as outside the function scope.




Venlig Hilsen / Best Regards
Rasmus Prentow

www.rasmusprentow.dk  <http://rasmusprentow.dk/>
me@rasmusprentow.dk

[image: Facebook] <http://facebook.com/pseduo> [image: Twitter]
<http://twitter.com/rasmusprentow> [image: Linkedin]
<https://www.linkedin.com/pub/rasmus-prentow/33/88/8b>

On Mon, Feb 27, 2017 at 8:52 AM, François Beaufort <notifications@github.com

**Comment by beaufortfrancois** [comment]
I believe arrow functions change the way `this` binds in functions. I would say arrow functions bind the lexical `this`.

**Comment by saspre** [comment]
It took me a while, but i realised you are right. What I meant is that it does not bind `this` to it self.

**Comment by beaufortfrancois** [comment]
Cool!

**Pull request closed without merging**
